language: go
env:
- GIMME_OS=linux GIMME_ARCH=arm GIMME_GOARM=7
go:
- '1.10'
script:
- export ARCH=arm
- export ARM=7
- cd rswe
- go build -ldflags "-s -w"
deploy:
  provider: releases
  api_key:
    secure: LqLaRtrzaTDVKtprH97jmeKLgaj7a6QXGn0Affl+6+Sz4FQEFJBavE0YjCo6deni/lQVTFcRLFrT7YXLvTgpNmkoXM3zS0E3X9FDhCxpHgqcKZSmW7AQuanYEARMxzPfBYZWAWGMorQCruxdqGjIta5RANsWs1s4D6spr7VKb/LCb6lD9RQJiRmoMXE2foyzCt9cBu2TPexrC6n5hw1BPKzNuHozaucY14vN0lVewU11r+xFvl/iiuMxUPBUY5CL9FM8dFAgYujkpO+DfZu/1r/HZynN1pUlj/yQ6v+9TNIcpcKkAkIvmirV54KIw2km3YH8uQoerxu2KftjhO5HYa/2JCPQ/AdftsmRrwepu+8tYRX8fNbID5Ri59glQUQ6Dp4vDaEVUFJJfYLOBwFaB72c7EGFSEAFltmBQDsXioGfHAP7JX9WIMi7s6bpLfoHK40FMukppr4IbMTtG+KkeXziL7IbJEJCePWsioDtv6BVlktR8NEy2+eqXjMENayLZHZr5Pr5mfhw7QOT7yrYEqS/oKbjjs9N1e+poTLcCTkeFjUX7e0d5fDPPPJQ0rz2BuOYtgnxZKf6Hs+aRniPsSBFBu4tpgrbs518zLASoEpumjCG24HOLeUfniZvk5u7fM/xMeHBYZWnB3uOvudqBN4tysb44RSQMBBL3vBUXyQ=
  file: rswe
  skip_cleanup: true
