language: go
env:
- GIMME_OS=linux GIMME_ARCH=arm GIMME_GOARM=7
go:
- '1.10'
script:
- export ARCH=arm
- export ARM=7
- cd monitor
- go build -ldflags "-s -w"
deploy:
  provider: releases
  api_key:
    secure: sAWdfx9D4i5VEbeFK1Wnb+ySiIuFKk0mO2O3QSjVmyqg6mASJLtpV4GImkJen/cXKFWlbjECif7TbEPuDYc97TD4CyEdoGUiWODz7zY0/x/hCAj+eodF5wVpP1aNbpHKhz04giHx2hCzMpfjChGHTgMtYuYOlbL27F9hfbKIqZlNAddbsxXoyWHeoRvJIAS8avp0fpUlNGxQar6ceitNHvEksO8kbb+xipcRBA1zbp0d05lkyXLoLwrb/3rFkg4o1TjV/6JQeuAf6g2L408UNJWzeuX8RSPXHdQQhaEFqUGC+Q+qtxQodMnJHCuhW7jkx4iinlgTOX/d1fOHkwJ6IHo9azCoBSaj4lk98DjrXP0Cc5m7aGROB1lgNAlQWfwRZcECWalSiDLe0RcEC+QVviMqYto06jdYzrEkqP9aSuh+HeDHvinZ9Gdrx1YcG8F1VfQSPppySQNTEawKyadJXi4rMy+BfPnaYtNSAmUO1KsC8lxyUCrfXtlhCPUI5WE1PuhxPcOjlqj0CHb9Az1/LwhihC2gePI+ReFtChrlD2cYUuYfda+vxAYpn+cji3zhOM/ow3LD1bg551ppTdWv1zdIud/0mHiUtKF5AnGL6SlQc2Cz3XrM9qoJ0MWCW7kM+9esmCjntaHqv5i5bZXRuYeqTo5df9ytBVb7Cej+/1Q=
  file: rswe
  skip_cleanup: true
